stages:
    - test

test-staging:
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    image: golang
    stage: test
    tags:
        - go-runner
    before_script:
        - export GO_PROJECT_NAMESPACE="$GOPATH/src/github.com/blocktree"
        - echo $GO_PROJECT_NAMESPACE
        - mkdir -p $GO_PROJECT_NAMESPACE
        - ln -srf $(pwd) $GO_PROJECT_NAMESPACE
        - export GO_PROJECT_PATH="$GO_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
        - echo $GO_PROJECT_PATH
        - cd $GO_PROJECT_PATH
        - rm -rf release
    script:
        - cd $GO_PROJECT_PATH
        - echo $(pwd)
        - ls
        # - go test ./openwsdk
    environment:
        name: staging
